### ISSUE TITLE
貌似缺少httpcore依赖,并且添加jar后某些方法调用扔不能通过编译

### ISSUE THREAD

**Issue by chunyisong** [huntermr/FastAndroid#4]
你好,我在Android studio 导入这个FastAndroid后,build失败,缺少 HttpEntity等类,我试着手工加入httpcore-4.4.4.jar到app/libs目录rebuild仍然失败.是不是缺少某些依赖?
下面是未添加httpcore-4.4.4.jar时build的信息
Executing tasks: [clean, :app:generateDebugSources, :app:generateDebugAndroidTestSources, :app:compileDebugSources, :app:compileDebugAndroidTestSources]

Configuration on demand is an incubating feature.
:clean UP-TO-DATE
:MyDaoGenerator:clean UP-TO-DATE
:app:clean
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:app:prepareComAndroidSupportAnimatedVectorDrawable2320Library
:app:prepareComAndroidSupportAppcompatV72320Library
:app:prepareComAndroidSupportSupportV42320Library
:app:prepareComAndroidSupportSupportVectorDrawable2320Library
:app:prepareComMakeramenRoundedimageview201Library
:app:prepareComSquareupLeakcanaryLeakcanaryAndroid131Library
:app:prepareDeHdodenhofCircleimageview130Library
:app:prepareDebugDependencies
:app:compileDebugAidl
:app:compileDebugRenderscript
:app:generateDebugBuildConfig
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources
:app:mergeDebugResources
:app:processDebugManifest
:app:processDebugResources
:app:generateDebugSources
:app:preDebugAndroidTestBuild UP-TO-DATE
:app:prepareDebugAndroidTestDependencies
:app:compileDebugAndroidTestAidl
:app:processDebugAndroidTestManifest
:app:compileDebugAndroidTestRenderscript
:app:generateDebugAndroidTestBuildConfig
:app:generateDebugAndroidTestAssets UP-TO-DATE
:app:mergeDebugAndroidTestAssets
:app:generateDebugAndroidTestResValues UP-TO-DATE
:app:generateDebugAndroidTestResources
:app:mergeDebugAndroidTestResources
:app:processDebugAndroidTestResources
:app:generateDebugAndroidTestSources
:app:processDebugJavaRes UP-TO-DATE
:app:compileDebugJavaWithJavac
G:\androidWorkspace\FastAndroid\app\src\main\java\com\hunter\fastandroid\net\AsyncHttpNetCenter.java:11: 错误: 程序包org.apache.http不存在
import org.apache.http.HttpEntity;
                      ^
G:\androidWorkspace\FastAndroid\app\src\main\java\com\hunter\fastandroid\net\AsyncHttpNetCenter.java:12: 错误: 程序包org.apache.http.protocol不存在
import org.apache.http.protocol.HTTP;
                               ^
G:\androidWorkspace\FastAndroid\app\src\main\java\com\hunter\fastandroid\net\AsyncHttpNetCenter.java:169: 错误: 找不到符号
                            String url, HttpEntity entity, String contentType, AsyncHttpResponseHandler responseHandler) {
                                        ^
  符号:   类 HttpEntity
  位置: 类 AsyncHttpNetCenter
G:\androidWorkspace\FastAndroid\app\src\main\java\com\hunter\fastandroid\net\AsyncHttpNetCenter.java:186: 错误: 找不到符号
                     String url, RequestParams requestParams, HttpEntity entity, String contentType, AsyncHttpResponseHandler responseHandler) {
                                                              ^
  符号:   类 HttpEntity
  位置: 类 AsyncHttpNetCenter
G:\androidWorkspace\FastAndroid\app\src\main\java\com\hunter\fastandroid\net\TransactionAsyncHttpStringHandler.java:6: 错误: 程序包org.apache.http不存在
import org.apache.http.Header;
                      ^
G:\androidWorkspace\FastAndroid\app\src\main\java\com\hunter\fastandroid\net\TransactionAsyncHttpStringHandler.java:22: 错误: 找不到符号
    public void onFailure(int statusCode, Header[] headers, String responseString, Throwable throwable) {
                                          ^
  符号:   类 Header
  位置: 类 TransactionAsyncHttpStringHandler
G:\androidWorkspace\FastAndroid\app\src\main\java\com\hunter\fastandroid\net\TransactionAsyncHttpStringHandler.java:27: 错误: 找不到符号
    public void onSuccess(int statusCode, Header[] headers, String responseString) {
                                          ^
  符号:   类 Header
  位置: 类 TransactionAsyncHttpStringHandler
G:\androidWorkspace\FastAndroid\app\src\main\java\com\hunter\fastandroid\net\AsyncHttpNetCenter.java:11: 错误: 程序包org.apache.http不存在
import org.apache.http.HttpEntity;
                      ^
G:\androidWorkspace\FastAndroid\app\src\main\java\com\hunter\fastandroid\net\AsyncHttpNetCenter.java:12: 错误: 程序包org.apache.http.protocol不存在
import org.apache.http.protocol.HTTP;
                               ^
G:\androidWorkspace\FastAndroid\app\src\main\java\com\hunter\fastandroid\net\AsyncHttpNetCenter.java:169: 错误: 找不到符号
                            String url, HttpEntity entity, String contentType, AsyncHttpResponseHandler responseHandler) {
                                        ^
  符号:   类 HttpEntity
  位置: 类 AsyncHttpNetCenter
G:\androidWorkspace\FastAndroid\app\src\main\java\com\hunter\fastandroid\net\AsyncHttpNetCenter.java:186: 错误: 找不到符号
                     String url, RequestParams requestParams, HttpEntity entity, String contentType, AsyncHttpResponseHandler responseHandler) {
                                                              ^
  符号:   类 HttpEntity
  位置: 类 AsyncHttpNetCenter
G:\androidWorkspace\FastAndroid\app\src\main\java\com\hunter\fastandroid\net\TransactionAsyncHttpStringHandler.java:6: 错误: 程序包org.apache.http不存在
import org.apache.http.Header;
                      ^
G:\androidWorkspace\FastAndroid\app\src\main\java\com\hunter\fastandroid\net\TransactionAsyncHttpStringHandler.java:22: 错误: 找不到符号
    public void onFailure(int statusCode, Header[] headers, String responseString, Throwable throwable) {
                                          ^
  符号:   类 Header
  位置: 类 TransactionAsyncHttpStringHandler
G:\androidWorkspace\FastAndroid\app\src\main\java\com\hunter\fastandroid\net\TransactionAsyncHttpStringHandler.java:27: 错误: 找不到符号
    public void onSuccess(int statusCode, Header[] headers, String responseString) {
                                          ^
  符号:   类 Header
  位置: 类 TransactionAsyncHttpStringHandler
G:\androidWorkspace\FastAndroid\app\src\main\java\com\hunter\fastandroid\net\AsyncHttpNetCenter.java:45: 错误: 找不到符号
    public static final String CONTENT_ENCODING = HTTP.UTF_8;
                                                  ^
  符号:   变量 HTTP
  位置: 类 AsyncHttpNetCenter
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
8 个错误

 FAILED

**Comment by huntermr** [comment]
请尝试使用最新版asynchttpAndroid依赖

**Comment by chunyisong** [comment]
我使用的就是最新的了,com.loopj.android:android-async-http:1.4.9
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'de.greenrobot:greendao:1.3.7'
    compile 'com.jakewharton:butterknife:7.0.1'
    compile 'com.loopj.android:android-async-http:1.4.9'
    compile 'com.squareup.okhttp:okhttp:2.5.0'
    compile 'de.hdodenhof:circleimageview:1.3.0'
    compile 'com.makeramen:roundedimageview:2.0.1'
    compile 'com.google.code.gson:gson:2.4'
    compile 'com.android.support:appcompat-v7:23.2.0'
    compile 'com.android.support:support-v4:23.2.0'
    debugCompile 'com.squareup.leakcanary:leakcanary-android:1.3.1'
    releaseCompile 'com.squareup.leakcanary:leakcanary-android-no-op:1.3.1'
}

**Comment by chunyisong** [comment]
@huntermr 问题已经解决了,在Android 6.0(API23)  httpclient相关的类已经被去掉,只在optional目录下留下了一个org.apache.http.legacy.jar,但是android-async-http 依赖的是cz.msebera.android:httpclient:4.3.6,这个为android提供的类库已经包处理了httpclient相关的部分
所以只需将代码种引用的HttpClient中的类修改为cz.msebera.android包下即可;另外,由于字符集在sdk已经提供了StandardCharsets类来提供便捷访问,所以对httpclient中字符编码的引用可以替换为StandardCharsets.
这是修改后的build.gradle:
apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.3"

```
sourceSets {
    main {
        java.srcDirs = ['src/main/java', 'src/main/java-gen']
        jniLibs.srcDirs = ['libs']
    }
}

defaultConfig {
    applicationId "com.hunter.fastandroid"
    minSdkVersion 19
    targetSdkVersion 23
    versionCode 3
    versionName "1.3"
}
buildTypes {
    release {
        minifyEnabled false
        proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
    }
}
```

}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'de.greenrobot:greendao:1.3.7'
    compile 'com.jakewharton:butterknife:7.0.1'
    compile 'com.loopj.android:android-async-http:1.4.9'
    compile 'com.squareup.okhttp:okhttp:2.5.0'
    compile 'de.hdodenhof:circleimageview:1.3.0'
    compile 'com.makeramen:roundedimageview:2.0.1'
    compile 'com.google.code.gson:gson:2.4'
    compile 'com.android.support:appcompat-v7:23.2.0'
    compile 'com.android.support:support-v4:23.2.0'
    debugCompile 'com.squareup.leakcanary:leakcanary-android:1.4-beta1'
    releaseCompile 'com.squareup.leakcanary:leakcanary-android-no-op:1.4-beta1'
    testCompile 'com.squareup.leakcanary:leakcanary-android-no-op:1.4-beta1'
}
